version: '2'

networks:
  appwebnet:

services:
  appnodejs:
    build: ./app
    ports:
      - 8080:8080
    networks:
      - appwebnet

  bbdd:
    image: 'redis:alpine'
    networks:
      appwebnet:
        aliases:
          - superdatabase

  expressfirstserver:
    build: ./express-first-server
    ports:
      - 8081:8081
