version: '1'

networks:
  appwebnet:

services:
  bbdd:
    image: 'redis:alpine'
    networks:
      appwebnet:
        aliases:
          - superdatabase

  appnodejs:
    build: ./app
    ports:
      - 8080:8080
    depends_on:
      - bbdd
    networks:
      - appwebnet