version: '1'

networks:
  appwebnet:

volumes:
  mongodata:

services:
  mongodb:
    image: mongo
    container_name: mongoDB
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: felipax
      MONGO_INITDB_ROOT_PASSWORD: Misterio0804
    networks:
      appwebnet:
        aliases:
          - mongoDB
    volumes:
      - mongodata:/data/db
    restart: always

  nestjsfirstserver:
    build: ./nest-firstserver
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    networks:
      - appwebnet
